### PR TITLE
Add kernel version check

### LINKED ISSUE #48: Bias resistor kernel version check
So I learned yesterday that bias resistor settings are a recent addition to the Linux kernel (v5.5). In all my digging to get to the bottom of the ambiguous *error 22*s I was getting, I found out that `ioctl` calls to `pinctrl` should allow control of bias resistors (I have not looked into how yet).

I was going to implement kernel version checks and have my downstream software decide when to use this alternate method, but then I thought why do that when I can contribute it upstream to the library!

For the cdev class it will be pretty easy to add branching to use the alternate method if a bias setting is specified, but I wanted your input on how to do it for sysfs or if it should be done. My thought is just to add a named arg `bias` to the sysfs class init function. That would maintain backwards compatibility and not break the logic that counts unnamed args to determine if the user is trying to get a sysfs or cdev instance. What are you thoughts on this?

Edit: using `pinctrl` we could actually expand the sysfs class to offer all of the settings that cdev does with the exception of `edge` and `label`.

### PR DESCRIPTION
**Pull request by CrazyIvan359**
Fixes #48 as discussed

### CODE REVIEW

**Comment by vsergeev** [comment]
Sorry about the delay. Thanks. Cherry-picked in 9c1a4f3 in devel.

**Comment by CrazyIvan359** [comment]
Just saw that you change from my list comprehension to the `*` sequence expansion, I don't think that works in Python 2 which is why I used list comp in the error message.

**Comment by vsergeev** [comment]
@CrazyIvan359 Are you thinking of an older Python 2? It works in Python 2.7:

```
Python 2.7.18 (default, Sep  5 2020, 11:17:26) 
[GCC 10.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> version = (1, 2)
>>> "foobar {}.{}".format(*version)
'foobar 1.2'
>>> 
```

**Comment by CrazyIvan359** [comment]
Hmm... Maybe it's lists you can't do it with then? I remember I've had errors thrown at me for using that operator in 2.7 before. If it works here then all good!

**Comment by vsergeev** [comment]
Lists work too. Maybe you ran into this one: https://stackoverflow.com/questions/22257930/python-2-tuple-list-unpacking-using-star-throws-syntaxerror , which is Python 3 only. In any case, I tested the current code with both 2 and 3, so we should be good.

**Comment by CrazyIvan359** [comment]
That looks familiar, yes.

**Pull request closed without merging**
